# Generated by Django 4.1.1 on 2022-09-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Mobiles and Tablets', 'Mobiles and Tablets'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Movie Tickets', 'Movie Tickets'), ('Baby Products', 'Books'), ('Books', 'Baby Products'), ('Groceries', 'Groceries'), ('Home Furnishings', 'Home Furnishings'), ('Jewellery', 'Jewellery')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.ManyToManyField(to='crm.tag')),
            ],
        ),
    ]
